version: '3.8'

services:
  web:
    build: .
    container_name: fuel_tracker_web
    ports:
      - "8089:80"
    volumes:
      - .:/var/www/html
      - ./logs:/var/www/html/logs
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=fuel_database
      - DB_USER=fuel_user
      - DB_PASS=fuel_password
      - DB_ROOT_PASS=root_password
    networks:
      - fuel_network
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: fuel_tracker_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fuel_database
      MYSQL_USER: fuel_user
      MYSQL_PASSWORD: fuel_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - fuel_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: fuel_tracker_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - fuel_network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  fuel_network:
    driver: bridge
